// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqffkumomjzzobwvizjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZmZrdW1vbWp6em9id3ZpempqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDQ5NjQsImV4cCI6MjA2ODc4MDk2NH0.69EATJCPZlk8B5mKpIdyKKoxuJcJoVBSus7mnh0LaIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});